[package]
name = "new"
version = "0.1.0"
edition = "2021"

[dependencies]
text_io = "0.1"
rand = "0.8.5"

[[bin]]
name = "project"
path = "src/project.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "trait"
path = "src/trait.rs"

[[bin]]
name = "add"
path = "src/add.rs"

[[bin]]
name = "NumberGuess"
path = "src/NumberGuess.rs"

[[bin]]
name = "StudentRecord"
path = "src/StudentRecord.rs"

[[bin]]
name = "lms"
path = "src/lms.rs"